// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://apwtrcenxujazqlvyrps.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFwd3RyY2VueHVqYXpxbHZ5cnBzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2MTE4NTEsImV4cCI6MjA1OTE4Nzg1MX0.m8j1vp_YWA91B8VPbJFTRaJh-vLHmnb5ghK4DcIBQ9M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);